J72443Restaurant/Pages/Admin/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using J72443Restaurant.Data;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;

namespace J72443Restaurant.Pages.Admin
{
    [Authorize(Roles = "Admin")]
    public class EditModel : PageModel
    {
        private AppDbContext _db;
        [BindProperty]
        public Food food { get; set; }
        [BindProperty]
        public IFormFile Pic { get; set; }
        private readonly IHostingEnvironment _he;

        public EditModel(AppDbContext db, IHostingEnvironment he)
        {
            _db = db;
            _he = he;
        }


        public async Task<IActionResult> OnGetAsync(int id)
        {
            food = await _db.Foods.FindAsync(id);
            if (food == null)
            {
                return RedirectToPage("/menuList");
            }
            return Page();

        }

        public async Task <IActionResult> OnPostSaveAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            if (Pic != null)
            {
                var filename = Path.Combine(_he.WebRootPath, "uploaded_image", Path.GetFileName(Pic.FileName));
                food.Image = Path.Combine("uploaded_image", Path.GetFileName(Pic.FileName));
                Pic.CopyTo(new FileStream(filename, FileMode.Create));
            }

            _db.Entry(food).State = EntityState.Modified;
            if(food.Image == null)
            {
                _db.Entry(food).Property(f => f.Image).IsModified = false;
            }

            try
            {

                await _db.SaveChangesAsync();

            }
            catch (DbUpdateConcurrencyException e)
            {
                throw new Exception($"Menu {food.ID} not found", e);
            }

            return RedirectToPage("/menuList");
        }
    }
}

J72443Restaurant/Pages/Admin/addmenu.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using J72443Restaurant.Data;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace J72443Restaurant
{

    [Authorize(Roles = "Admin")]
    public class addmenuModel : PageModel
    {
        private AppDbContext _db;
        [BindProperty]
        public Food food { get; set; }
        [BindProperty]
        public IFormFile Pic { get; set; }
        private readonly IHostingEnvironment _he;

        public addmenuModel(AppDbContext db, IHostingEnvironment he)
        {
            _db = db;
            _he = he;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            if(Pic != null)
            {
                var filename = Path.Combine(_he.WebRootPath, "uploaded_image", Path.GetFileName(Pic.FileName));
                food.Image = Path.Combine("uploaded_image", Path.GetFileName(Pic.FileName));
                Pic.CopyTo(new FileStream (filename, FileMode.Create));
            }

            _db.Foods.Add(food);
            await _db.SaveChangesAsync();

            return RedirectToPage("/menuList");
        }
      
    }
}

J72443Restaurant/Pages/Admin/Edit.cshtml
@page
@model J72443Restaurant.Pages.Admin.EditModel
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers

<link href="~/css/fix.css" rel="stylesheet" />

<div id="editMenu">


    <div class="main-container">





        <div id="img-zoomer-box">
            <img id="img1" src="@Url.Content("~/" + Model.food.Image)" alt="@Model.food.Image" />
            <div id="img2"></div>
        </div>

        <h2>Menu: @Model.food.FoodName</h2>

        <form method="post" enctype="multipart/form-data">
            <table>
                <tr>
                    <td>
                        <label>Name: </label>
                        <div>
                            <input asp-for="food.ID" type="hidden" />
                            <input asp-for="food.FoodName">
                        </div>
                    </td>

                    <td>
                        <label>Price </label>
                        <div>
                            <input asp-for="food.Price">
                        </div>
                    </td>

                    <td>
                        <label>Description: </label>
                        <div>
                            <input asp-for="food.Description">
                        </div>
                    </td>

                    <td>
                        <label>Select Image</label>
                        <div>
                            <input type="file" name="Pic" />
                        </div>
                    </td>

                    <td>
                        <div><button type="submit" asp-page-handler="Save">Save</button></div>
                    </td>
                </tr>
            </table>
        </form>

    </div>

</div>

J72443Restaurant/Pages/Admin/addmenu.cshtml
@page
@model J72443Restaurant.addmenuModel
@{
    ViewData["Title"] = "addmenu";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers

<link href="~/css/fix.css" rel="stylesheet" />


    <div id="addMenu">

        <div class="main-container">


            <h2>Add Menu Page</h2>

            <form method="post" enctype="multipart/form-data">
                <div asp-validation-summary="All"></div>

                <table>
                    <thead>
                        <tr>
                            <th scope="col">Food Name</th>
                            <th scope="col">Price</th>
                            <th scope="col">Description</th>
                            <th scope="col">Upload Photo</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td scope="row" data-label="Food Name"><input asp-for="food.FoodName"></td>
                            <td data-label="Price"><input asp-for="food.Price" inputmode="numeric"></td>
                            <td data-label="Description"><input asp-for="food.Description"></td>
                            <td data-label="Upload Photo">
                                <input type="file" name="Pic" />
                            </td>
                            <td data-label="Submit"><input type="submit" /></td>
                        </tr>
                    </tbody>

                </table>
            </form>
        </div>
    </div>