J72443Restaurant/Pages/Checkout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using J72443Restaurant.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Stripe;

namespace J72443Restaurant.Pages
{
    public class CheckoutModel : PageModel
    {
        private readonly AppDbContext _db;
        private readonly UserManager<ApplicationUser> _UserManager;
        public IList<CheckoutItem> Items { get; private set; }
        public OrderHistory Order = new OrderHistory();

        public decimal Total = 0;
        public long AmountPayable = 0;


        public CheckoutModel(AppDbContext db, UserManager<ApplicationUser> UserManager)
        {
            _db = db;
            _UserManager = UserManager;
        }

        public async Task OnGetAsync()
        {
            var user = await _UserManager.GetUserAsync(User);
            CheckoutCustomer customer = await _db
            .CheckoutCustomers
            .FindAsync(user.Email);

            Items = _db.CheckoutItems.FromSql(
                "SELECT Foods.ID, Foods.Price, " +
                "Foods.FoodName, " +
                "BasketItems.BasketID, BasketItems.Quantity " +
                "FROM Foods INNER JOIN BasketItems " +
                "ON Foods.ID = BasketItems.StockID " +
                "WHERE BasketID = {0}", customer.BasketID
                ).ToList();

            Total = 0; 
            foreach (var item in Items)
            {
                Total = Total + (item.Quantity * item.Price);
            }

            AmountPayable = (long)(Total * 100);

        }

        public async Task<IActionResult> OnPostBuyAsync(int itemID)
        {

        
            var currentOrder = _db.OrderHistories.FromSql("SELECT * From OrderHistories").OrderByDescending(b => b.OrderNo).FirstOrDefault();

            if (currentOrder == null)
            {
                Order.OrderNo = 1;
            }
            else
            {
                Order.OrderNo = currentOrder.OrderNo + 1;
            }

            var user = await _UserManager.GetUserAsync(User);
            Order.Email = user.Email;
            _db.OrderHistories.Add(Order);

            CheckoutCustomer customer = await _db
                .CheckoutCustomers
                .FindAsync(user.Email);

            var basketItems =
                _db.BasketItems
                .FromSql("SELECT * From BasketItems " +
                "WHERE BasketID = {0}", customer.BasketID)
                .ToList();

            Total = 0;

            foreach (var item in basketItems)
            {
                Data.OrderItem oi = new Data.OrderItem
                {
                    OrderNo = Order.OrderNo,
                    StockID = item.StockID,
                    Quantity = item.Quantity
                };

                _db.OrderItems.Add(oi);   

            } 

            await _db.SaveChangesAsync();

            return RedirectToPage("/Index");
        }

        public async Task<IActionResult> OnPostChargeAsync(string stripeEmail, string stripeToken, long amount)
        {
            var currentOrder = _db.OrderHistories.FromSql("SELECT * From OrderHistories").OrderByDescending(b => b.OrderNo).FirstOrDefault();

            if (currentOrder == null)
            {
                Order.OrderNo = 1;
            }
            else
            {
                Order.OrderNo = currentOrder.OrderNo + 1;
            }

            var user = await _UserManager.GetUserAsync(User);
            Order.Email = user.Email;
            _db.OrderHistories.Add(Order);

            CheckoutCustomer customer = await _db
                .CheckoutCustomers
                .FindAsync(user.Email);

            var basketItems =
                _db.BasketItems
                .FromSql("SELECT * From BasketItems " +
                "WHERE BasketID = {0}", customer.BasketID)
                .ToList();


            foreach (var item in basketItems)
            {
                Data.OrderItem oi = new Data.OrderItem
                {
                    OrderNo = Order.OrderNo,
                    StockID = item.StockID,
                    Quantity = item.Quantity
                };

                _db.OrderItems.Add(oi);
                _db.BasketItems.Remove(item);

            }
                await _db.SaveChangesAsync();

                var customers = new CustomerService();
                var charges = new ChargeService();

                var customer_ = customers.Create(new CustomerCreateOptions
                {
                    Email = stripeEmail,
                    Source = stripeToken
                });

                var charge = charges.Create(new ChargeCreateOptions
                {
                    Amount = amount,
                    Description = "J72443 Restaurant Charge",
                    Currency = "gbp",
                    CustomerId = customer_.Id
                });
            
            return RedirectToPage("/Account/Success");
        }

        public async Task<IActionResult> OnPostDeleteAsync(int itemID)
        {
            var user = await _UserManager.GetUserAsync(User);
            Order.Email = user.Email;

            CheckoutCustomer customer = await _db
                .CheckoutCustomers
                .FindAsync(user.Email);

                _db.BasketItems
                .FromSql("SELECT * From BasketItems " +
                "WHERE BasketID = {0}", customer.BasketID)
                .ToList();

            var item = await _db.BasketItems.FindAsync(itemID, customer.BasketID);
            if (item != null)
            {
                _db.BasketItems.Remove(item);
            
                await _db.SaveChangesAsync();
            }
            return RedirectToPage();
        }

        public async Task<IActionResult> OnUpdateAsync(int itemID)
        {
            var user = await _UserManager.GetUserAsync(User);

            CheckoutCustomer customer = await _db
            .CheckoutCustomers
            .FindAsync(user.Email);

            var item = _db.BasketItems.FromSql("SELECT * FROM BasketItems WHERE StockID = {0}" + " AND BasketID = {1}", itemID, customer.BasketID)
            .ToList()
            .FirstOrDefault();

            if (item == null)
            {
                BasketItem newItem = new BasketItem
                {
                    BasketID = customer.BasketID,
                    StockID = itemID,
                    Quantity = 1
                };
                _db.BasketItems.Add(newItem);
                await _db.SaveChangesAsync();
            }
            else
            {
                item.Quantity = item.Quantity + 1;
                _db.Attach(item).State = EntityState.Modified;
                try
                {
                    await _db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException e)
                {
                    throw new Exception($"Basket not found!", e);
                }
            }
            return RedirectToPage("/Checkout");
        }
    }

}

J72443Restaurant/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using J72443Restaurant.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;


namespace J72443Restaurant.Pages
{
    public class ContactModel : PageModel
    {

        [BindProperty]
        public ContactFormModel Contact { get; set; }


        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }


            var mailbody = $@"A customer has just sent you an email!,

            Customer Information:

            Name: {Contact.Name}
            LastName: {Contact.LastName}
            Email: {Contact.Email}
            Message: ""{Contact.Message}""


            Cheers,
            J72443 Web Application contact form";

            SendEmail(mailbody);

            // create and send the mail here

            return RedirectToPage("Account/MessageSuccess");
        }


        private void SendEmail(string mailbody)
        {
            using (var message = new MailMessage(Contact.Email, "Restaurantj72443@gmail.com"))
            {
                message.To.Add(new MailAddress("Restaurantj72443@gmail.com"));
                message.From = new MailAddress(Contact.Email);
                message.Subject = "New E-Mail from my website";
                message.Body = mailbody;

                using (var client = new SmtpClient("smtp.gmail.com", 587))
                {
                    client.EnableSsl = true;
                    client.UseDefaultCredentials = false;
                    client.Credentials = new NetworkCredential("Restaurantj72443@gmail.com", "Che19970704");
                    client.Send(message);

                }
            }
        }
    }
}

J72443Restaurant/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using J72443Restaurant.Data;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace J72443Restaurant.Pages
{
    public class IndexModel : PageModel
    {
        private readonly AppDbContext _db;
        public IList<Food> food { get; private set; }
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IHostingEnvironment _he;
        public IFormFile Pic { get; set; }

        public IndexModel(AppDbContext db, UserManager<ApplicationUser> userManager, IHostingEnvironment he)
        {
            _db = db;
            _he = he;
            _userManager = userManager;
        }
 
        public async Task<IActionResult> OnGetAsync(int id)
        {
            food = _db.Foods.FromSql("SELECT TOP 6 * FROM Foods ORDER BY Foods.ID DESC").ToList();
  
            return Page();
        }
    }
}

J72443Restaurant/Pages/menuList.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using J72443Restaurant.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace J72443Restaurant.Pages
{
    
    public class menuListModel : PageModel
    {

        private readonly AppDbContext _db;
        public IList<Food> food { get; private set; }
        [BindProperty]
        public string Search { get; set; }
        private readonly UserManager<ApplicationUser> _userManager;
        public menuListModel(AppDbContext db, UserManager<ApplicationUser> userManager)
        {
            _db = db;
            _userManager = userManager;
        }

        public void OnGet()
        {
            food = _db.Foods.FromSql("SELECT * FROM Foods").ToList();
        }

        public IActionResult OnPostSearch()
        {
            food = _db.Foods.FromSql("SELECT * FROM Foods WHERE FoodName LIKE " + "'" + Search + "%' OR FoodName LIKE" + "'%" + Search + "' OR Description LIKE '%" + Search + "%'")
                 .ToList();
            return Page();
        }

        [Authorize]
        public async Task<IActionResult> OnPostDeleteAsync(int itemID)
        {
            var item = await _db.Foods.FindAsync(itemID);
            if (item != null)
            {
                _db.Foods.Remove(item);
                await _db.SaveChangesAsync();
            }
            return RedirectToPage();
        }

        [Authorize]
        public async Task<IActionResult> OnPostBuyAsync(int itemID)
        {
            var user = await _userManager.GetUserAsync(User);
            CheckoutCustomer customer = await _db
            .CheckoutCustomers
            .FindAsync(user.Email);

            var item = _db.BasketItems.FromSql("SELECT * FROM BasketItems WHERE StockID = {0}" + " AND BasketID = {1}", itemID, customer.BasketID)
            .ToList()
            .FirstOrDefault();

            if (item == null)
            {
                BasketItem newItem = new BasketItem
                {
                    BasketID = customer.BasketID,
                    StockID = itemID,
                    Quantity = 1
                };
                _db.BasketItems.Add(newItem);
                await _db.SaveChangesAsync();
            }
            else
            {
                item.Quantity = item.Quantity + 1;
                _db.Attach(item).State = EntityState.Modified;
                try
                {
                    await _db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException e)
                {
                    throw new Exception($"Basket not found!", e);
                }
            }
            return RedirectToPage();
        }
    }

}

J72443Restaurant/Pages/userLogin.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace J72443Restaurant.Pages
{
    public class userLoginModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

J72443Restaurant/Pages/Checkout.cshtml
@page
@model J72443Restaurant.Pages.CheckoutModel
@{
    ViewData["Title"] = "Checkout";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@using J72443Restaurant.Data
@using Microsoft.Extensions.Options
@inject IOptions<StripeSettings> Stripe

<link href="~/css/map.css" rel="stylesheet" />

<div id="checkout">
    <div class="table-scroll main-container">

        <h2>Checkout</h2>

        <form method="post">
            <div asp-validation-summary="All"></div>

         
            <div class="res">
                <table>
                    <thead>
                        <tr>
                            <th scope="col" colspan="1">Items</th>
                            <th scope="col">QTY</th>
                            <th scope="col">Price</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    @foreach (var item in Model.Items)
                    {
                        <tbody>

                            <tr>
                                <td scope="row" class="book-title">@item.FoodName</td>
                                <td data-label="Quantity" class="item-qty"><input type="number" step="1" min="0" max="100" id="quantity" value=@item.Quantity></td>
                                <td data-label="Price" class="item-price">@item.Price.ToString("C")</td>
                                <td><input asp-page-handler="Delete" asp-route-itemID="@item.ID" class="deletebutton" name="delete" type="submit" value="Remove"></td>
                            </tr>
                        </tbody>
                    }
                    <tfoot>
                        <tr>
                            <td colspan="2">Total</td>
                            <td data-label="Total" colspan="2">@Model.Total.ToString("C")</td>
                        </tr>
                    </tfoot>

                </table>
             
                </div>
       
        </form>

        <br />

        <form asp-page-handler="Charge" asp-route-amount="@Model.AmountPayable" method="POST">
            <script src="//checkout.stripe.com/v2/checkout.js"
                    class="stripe-button"
                    data-key="@Stripe.Value.PublishableKey"
                    data-locale="auto"
                    data-description="J72443 Restaurant Charge"
                    data-amount="@Model.AmountPayable"
                    data-currency="GBP">
            </script>
        </form>

    </div>
</div>

J72443Restaurant/Pages/Contact.cshtml
@page
@model J72443Restaurant.Pages.ContactModel
@{
    ViewData["Title"] = "Contact";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<link href="~/css/map.css" rel="stylesheet" />


<div id="contactPage" class="container">
    <div class="innerwrap">

        <section class="section1 clearfix">
            <h1>Contact Us</h1>
        </section>

        <section class="section2 clearfix">
            <div class="col2 column1 first">
                <script src='https://maps.googleapis.com/maps/api/js?v=3.exp'></script>
                <div class="sect2gmap">
                    <div id='gmap_canvas'></div>
                    <div><small><a href="http://embedgooglemaps.com"> embed google maps </a></small></div>
                    <div><small><a href="http://freedirectorysubmissionsites.com/">free web directories</a></small></div>
                </div>

                <script type='text/javascript'>
                    function init_map() {
                        var myOptions = {
                            zoom: 18,
                            center: new google.maps.LatLng(4.885756, 114.931676),
                            mapTypeId: google.maps.MapTypeId.ROADMAP
                        };
                        map = new google.maps.Map(document.getElementById('gmap_canvas'), myOptions);
                        marker = new google.maps.Marker({
                            map: map,
                            position: new google.maps.LatLng(4.885756, 114.931676)
                        });
                        infowindow = new google.maps.InfoWindow({
                            content: '<strong>Location</strong><br>Find Us Here<br>'
                        });
                        google.maps.event.addListener(marker, 'click', function () {
                            infowindow.open(map, marker);
                        });
                        infowindow.open(map, marker);
                    }
                    google.maps.event.addDomListener(window, 'load', init_map);
                </script>

            </div>
            <div class="col2 column2 last">
                <div class="contactform">
                    <h3 class="formtitle">Contact Form</h3>
                    <form class="form form-horizontal" method="post">
                        <div asp-validation-summary="All"></div>
                        <div class="clearfix">
                            <input asp-for="Contact.Name" class="form-control" placeholder="First Name"/>
                            <span asp-validation-for="Contact.Name"></span>

                            <input asp-for="Contact.LastName" class="form-control" placeholder="Last Name" />
                            <span asp-validation-for="Contact.LastName"></span>

                        </div>
                        <div class="clearfix">
                            <input asp-for="Contact.Email" class="form-control" placeholder="Your Email" />
                            <span asp-validation-for="Contact.Email"></span>
                        </div>
                        <div class="clearfix">
                            <textarea asp-for="Contact.Message" rows="6" class="form-control" placeholder="Your Message..."></textarea>
                            <span asp-validation-for="Contact.Message"></span>
                        </div>

                        <button type="submit">Send</button>
                    </form>
                </div>

            </div>
        </section>

    </div>
</div>

J72443Restaurant/Pages/Index.cshtml
@page
@model J72443Restaurant.Pages.IndexModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers

@using Microsoft.AspNetCore.Identity
@using J72443Restaurant.Data
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<link href="~/css/stylesheet.css" rel="stylesheet" />

<div id="container">
    <div id="main">


        <div class="bgimg-1">
            <div class="caption">
                <div class="titleMessage">
                    <div class="heading caption">
                        <span class="main border">HALAL RESTAURANT</span>
                        <p class="sub typed"></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="article-1">
            <h3>Our Special Menus</h3>
            <br />
            <p>
                Enjoy our special menu with 20% discount for purchase $100 above! Free Medium Coca Cola with a $1 Minimum Purchase. More discounts to come. Stay tuned for our latest offer!
            </p>


            <div class="indexContainer">

                @foreach (var fd in Model.food)
                {
 
                    <img class="breakpoint three-columns" src="@Url.Content("~")\@fd.Image" alt="@fd.Image" />
                   
      
                }

            </div>

            <div class="ViewAllMenu">
                <a asp-page="/menuList">View All Menu</a>
            </div>


        </div>
        <div class="bgimg-2">
            <div class="caption">
                <span class="border">FREE DELIVERY</span>
            </div>
        </div>

        <div class="article-2">
            <div class="caption-2">
                <p>Free Medium Fries with a $1 Minimum Purchase.</p>
            </div>
        </div>

        <div class="bgimg-3">
            <div class="caption">
                <span class="border">BEST IN TOWN</span>
            </div>
        </div>

        <div class="article-3">
            <div class="caption-3">
                <p>We also support Uber Eat! Just download Uber Eat app, enter your location, choose HALAL Restaurant, and order!.</p>
            </div>
        </div>

        <div class="bgimg-1">
            <div class="caption">
                <span class="border">VISIT OUR STORE!</span>
            </div>
        </div>
    </div>
</div>

<script src="~/js/typed.min.js"></script>
<script>
    var typed = new Typed(".typed", {
        strings: ["Best Restaurant in UK.", "Ten Times Chef's World Champion.", "Premium Meals."],
        typeSpeed: 70,
        loop: true,
        startDelay: 1000,
        showCursor: false
    });
                    //Because I am using jQuery, I need to call the plugin from typed.min.js
</script>

J72443Restaurant/Pages/menuList.cshtml
@page
@model J72443Restaurant.Pages.menuListModel
@{
    ViewData["Title"] = "menuList";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}
<link href="~/css/stylesheet.css" rel="stylesheet" />
<link href="~/css/map.css" rel="stylesheet" />

@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers

@using Microsoft.AspNetCore.Identity
@using J72443Restaurant.Data
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


<div id="foodList" class="table-scroll main-container" >
    <h2 class="restaurantMenu">Our Restaurants Menu</h2>
    <form method="post">
        <table>
            <tr>
                <td><input asp-for="Search" placeholder="Seach Name or Description" /> <button type="submit" asp-page-handler="Search">Search</button></td>

            </tr>
        </table>
    </form>

    <form method="post">
        <table>
            <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Price</th>
                    <th scope="col">Description</th>
                    <th scope="col">Photo</th>
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <th></th>
                    }

                    @if (User.IsInRole("Admin"))
                    {
                        <th scope="col">Edit/Delete</th>
                    }
                </tr>
            </thead>

            @foreach (var fd in Model.food)
            {
                <tbody>
                    <tr>
                        <td scope="row" data-label="Food Name">@fd.FoodName</td>
                        <td data-label="Price">@fd.Price.ToString("C")</td>
                        <td data-label="Description">@fd.Description</td>
                        <td data-label="Photo">
                            <img src="@Url.Content(fd.Image)" alt="@fd.Image" />
                        </td>

                        @if (SignInManager.IsSignedIn(User))
                        {
                            <td>
                                <button type="submit" asp-page-handler="Buy" asp-route-itemID="@fd.ID">Add To Cart</button>
                            </td>
                        }

                        @if (User.IsInRole("Admin"))
                        {
                            <td>
                                <a asp-page="/Admin/Edit" asp-route-id="@fd.ID">edit</a>
                                <button type="submit" asp-page-handler="Delete" asp-route-id="@fd.ID">delete</button>
                            </td>
                        }
                    </tr>
                </tbody>
            }
        </table>
    </form>

</div>